#index:
#    path: /
#    controller: App\Controller\DefaultController::index
helloWorld:
  path: /hello
  controller: App\Controller\HelloWorldController::helloWorld

hello:
  path: /hello/{prenom}
  controller: App\Controller\HelloWorldController::hello
  requirements:
    prenom: '[a-zA-Z]+'

form:
  path: /form
  controller: App\Controller\HelloWorldController::form
  methods: GET

formReceive:
  path: /form
  controller: App\Controller\HelloWorldController::formReceive
  methods: POST

liste:
  path : /liste
  controller: App\Controller\HelloWorldController::liste

liste2:
  path : /liste2
  controller: App\Controller\HelloWorldController::liste2

loginForm:
    path: /login
    controller: App\Controller\Forms\LoginController::loginForm
    methods: GET|POST

creationCompteForm:
  path: /creation
  controller: App\Controller\Forms\CompteController::creationCompteForm
  methods: GET
creationPost:
  path: /creation
  controller: App\Controller\Forms\CompteController::creationPost
  methods: POST